---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: loadtest
spec:
  replicas: 2
  selector:
    matchLabels:
      name: load-test
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        image: weaveworksdemos/load-test:0.1.1
        command: ["/bin/sh"]
        args: ["-c", "while true; do curl -X GET http://front-end.sock-shop.svc.cluster.local/invalid-endpoint || true; sleep 1; done"]
        # Added healthcheck to ensure container restarts if it fails
        livenessProbe:
          httpGet:
            path: /invalid-endpoint
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
