---
apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop
  labels:
    app: sock-shop
    environment: production
  annotations:
    description: "Namespace for the Sock Shop microservices demo"
