---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      initContainers:
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'mkdir -p /etc/fluentd && cp /fluentd/etc/fluent.conf /etc/fluentd/fluent.conf']
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.16.5-debian-elasticsearch7-1.1
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-config