apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: {{ .Values.namespace }}
  labels:
    name: carts
spec:
  replicas: {{ .Values.carts.replicaCount }}
  selector:
    matchLabels:
      name: carts
  template:
    metadata:
      labels:
        name: carts
    spec:
      containers:
      - name: carts
        image: "{{ .Values.carts.image.repository }}:{{ .Values.carts.image.tag }}"
        env:
          - name: JAVA_OPTS
            value: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
        resources:
          limits:
            cpu: {{ .Values.carts.resources.limits.cpu }}
            memory: {{ .Values.carts.resources.limits.memory }}
          requests:
            cpu: {{ .Values.carts.resources.requests.cpu }}
            memory: {{ .Values.carts.resources.requests.memory }}
        ports:
          - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux